title: Mon site GitHub Pages
description: Bienvenue sur mon site, partageant mes projets IT et mes explorations techniques.
url: https://github.com/Footix32/Footix32.github.io
theme: jekyll-theme-slate
github:
  owner_name: Footix32
